module.exports = {
  "[来自抽取] {title}": "[From Collections] {title}",
  "你需要重新加载该页面才能抽取。请重新加载页面后再试一次": "You will need to reload the page to clip. Please reload the page and try again",
  "保存到": "Save to",
  "保存到Sadp抽取器云文档": "Save to Yuque Note",
  "保存失败，请重试！": "Failed to save, please try again!",
  "保存成功！": "Save success!",
  "其他": "Others",
  "划词抽取默认保存位置": "The default save location of wordmark clipping",
  "划词快捷指令": "Word shortcut command",
  "抽取": "Collections",
  "抽取到": "clip to",
  "抽取网址": "Clip url",
  "抽取选取的内容": "Clip selected content",
  "升级新版本": "New version",
  "即将上新": "Coming soon",
  "去云文档查看": "Go to Note",
  "云文档": "Note",
  "打开Sadp抽取器": "Open Yuque",
  "欢迎，请点击登录Sadp抽取器账户": "Welcome",
  "登录失败": "登录失败",
  "登录验证": "登录验证",
  "知识库": "Knowledge base",
  "立即查看": "View now",
  "结果": "result",
  "继续选取": "Continue selecting",
  "访问主页": "Visit homepage",
  "Sadp抽取器抽取": "Yuque clipping",
  "Sadp抽取器插件": "Yuque plugin",
  "Sadp抽取器浏览器插件": "Yuque browser plugin",
  "账户": "account",
  "退出登录": "Logout account",
  "退出账户": "Logout account",
  "选中文本时，展示划词快捷指令功能": "When the text is selected, the shortcut command function of word marking will be displayed",
  "选择抽取方式": "Choose clipping method",
  "通用设置": "General settings",
  "问题反馈": "Feedback"
};
